=== changshikang/JavaTest/src/xmlTest/studentdtd.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (name,age)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ATTLIST student id CDATA #FIXED "01">
       <!-- 定义一个属性的格式为：<!ATTLIST 元素名称 属性名称 属性的类型 属性的约束> 属性的类型： CDATA类型：
        普通的字符串
        属性的约束:
        // #REQUIRED： 必须的 // #IMPLIED： 属性不是必需的 // #FIXED value：属性值是固定的-->

=== changshikang/JavaTest/src/xmlTest/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE students SYSTEM 'studentdtd.dtd'>-->

<students
        <!--xmlns:xsi="http://www.w3.org/2001/XMLSchema"
        xmlns="http://www.itheima.cn/javase"
        xsi:schemaLocation="http://www.itheima.cn/javase person.xsd"-->
        >
    <student>
        <name><![CDATA[<<<<<>>>>>>!2133321]]></name>
        <age>25</age>

    </student>
    <student >
        <name>张三</name>
        <age>30</age>
    </student>
    <student>
        <name>李四</name>
        <age>20</age>
    </student>
</students>
        <!--    <Teachers>
                <Teacher name="teacher">
                    <name>一加</name>
                    <info><![CDATA[one plus]]></info>
                </Teacher>
            </Teachers>
        </Person>-->
